"""INITIAL MIGRATION

Revision ID: 682d7b37116b
Revises: 
Create Date: 2025-03-30 14:58:26.831026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682d7b37116b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('chapter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('chapter_id')
    )
    op.create_table('city_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('rent_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rent_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('salary_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_name')
    )
    op.create_table('learning_module',
    sa.Column('module_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('xp_award', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('experience_points', sa.Integer(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('goal',
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_name', sa.String(length=100), nullable=False),
    sa.Column('year_of_completion', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('quiz',
    sa.Column('quiz_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.chapter_id'], ),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_table('salary_transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.Enum('EARNING', 'DEDUCTION', name='transactiontype'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('user_progress',
    sa.Column('progress_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['learning_module.module_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('progress_id')
    )
    op.create_table('lesson',
    sa.Column('lesson_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.chapter_id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_table('user_quiz_progress',
    sa.Column('progress_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('progress_id')
    )
    op.create_table('user_lesson_progress',
    sa.Column('progress_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.lesson_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('progress_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lesson_progress')
    op.drop_table('user_quiz_progress')
    op.drop_table('lesson')
    op.drop_table('user_progress')
    op.drop_table('salary_transaction')
    op.drop_table('quiz')
    op.drop_table('goal')
    op.drop_table('user')
    op.drop_table('learning_module')
    op.drop_table('city_cost')
    op.drop_table('chapter')
    # ### end Alembic commands ###
