"""Sync progress table with remote

Revision ID: 91be98fe5fd2
Revises: 682d7b37116b
Create Date: 2025-03-30 18:48:05.436825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91be98fe5fd2'
down_revision = '682d7b37116b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_current_progress',
    sa.Column('progress_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_chapter_id', sa.Integer(), nullable=False),
    sa.Column('current_lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_chapter_id'], ['chapter.chapter_id'], ),
    sa.ForeignKeyConstraint(['current_lesson_id'], ['lesson.lesson_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('progress_id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('user_lesson_progress')
    op.drop_table('user_quiz_progress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_quiz_progress',
    sa.Column('progress_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], name='user_quiz_progress_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='user_quiz_progress_user_id_fkey'),
    sa.PrimaryKeyConstraint('progress_id', name='user_quiz_progress_pkey')
    )
    op.create_table('user_lesson_progress',
    sa.Column('progress_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.lesson_id'], name='user_lesson_progress_lesson_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='user_lesson_progress_user_id_fkey'),
    sa.PrimaryKeyConstraint('progress_id', name='user_lesson_progress_pkey')
    )
    op.drop_table('user_current_progress')
    # ### end Alembic commands ###
