"""Added rent column to User and AccountLog initialization

Revision ID: bb2d536a5ee5
Revises: 91be98fe5fd2
Create Date: 2025-04-05 20:12:58.816163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2d536a5ee5'
down_revision = '91be98fe5fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_balance', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('rent', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rent')
        batch_op.drop_column('account_balance')

    op.drop_table('account_log')
    # ### end Alembic commands ###
